### ISSUE TITLE
query bug with RegExp

### ISSUE THREAD

**Issue by minyoung90** [kawamataryo/vue-word-highlighter#1048] opened 2023-11-16 10:03 UTC
```html
<WordHighlighter :query="/ＳＴ１/i" :html-to-highlight="`<p>ＳＴ１</p>`"></WordHighlighter>
```

if you use above example, then you can check there is no highlight

**Comment by chouchouji** [comment] 2023-12-14 03:55
Can I take this issue? I am pleased to try to solve it.

**Comment by DannyFeliz** [comment] 2024-02-08 07:15
@chouchouji Please, take it, I'm facing this issue too.

**Comment by kawamataryo** [comment] 2024-02-15 06:45
@minyoung90 @DannyFeliz 

This appears to be a bug that was introduced when the diacritics sensitivity option was added. Due to the diacritics library, a mismatch occurs when the string comparison transforms the query's ST to a half-width ST. As a workaround, you can prevent this bug by setting the `diacriticsSensitive` option to `true`. 

```
// it worked.
<WordHighlighter :query="/ＳＴ１/i" :html-to-highlight="`<p>ＳＴ１</p>`" :diacriticsSensitive="true"></WordHighlighter>
```

[Reproduction is here.](https://play.vuejs.org/#eNp9Uktu2zAQvQrLjVsgktBmJyhGfwHSLtqiKdANF1GlscSUIlly5DgwfIieJVn6Tr5ChpQtJ4bhhQBy3pvhm/e05B+sTec98JwXvnLSIvOAvZ0KLTtrHLIlczBjKzZzpmMTok5G6Ldx9ZVsWkUfghsoghMnuSMoafeY4EILXRntkXW+YRdh6uvJFShlwhxVv5q82RGk/yxLEoOy8tegPR3msG1B1wMRi2xQSzrpgtBZVSLQjbHCTuuxnbbZ9ueskNr2yPDewoXgVQvV3z9mITibJ52pQVHx6MuCT4ssOEKzD1fO//Xg7qkz26wfNuvHzfp/Jmlk3mKnEjR7D4hzQ9JGWhh5E5h7scko9qSUAw0krMieOcDP+JBP0pU2vfVGU7jLoJ6GRsALnrNYCbXjceWEtIjW51kGvkt9mx0jvn+bvkvPQ7qMrYRe0ePoKcWZbA6erkxnpQL33aKklF9IKOkvuPsaayHfs109ZnSkfusptqDwhwMPLvgyYli6BnCAL6+/wYLOI0g594rYJ8Cf4I3qg8aB9rHXNcl+xotqv0QnpW5++csFhny2SwWh0Y3Ij/Z+OrH6Xu45+bhzcfUENGNESw==) please give it a try.

**Comment by kawamataryo** [comment] 2024-02-15 06:58
@chouchouji 

I'm sorry for the delayed response. I appreciate your offer. However, since some time has passed, I will make the corrections myself. In the future, feel free to create a PR directly without having to ask.

**Comment by kawamataryo** [comment] 2024-02-15 07:46
This bug has been fixed in v1.2.4.

**Comment by DannyFeliz** [comment] 2024-02-15 14:09
@kawamataryo Thanks for this fix 🙌🏻

**Closed** 2024-02-16 00:30 UTC
Labels: bug

**Comment by minyoung90** [comment] 2024-03-29 06:52
thanks for fix!
